spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casava-library
    username: postgres
#    add postgres password
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true